removing dependency to tensorflow
eriklindernoren/PyTorch-YOLOv3 pull request #412
Opened 2020-01-24 09:52 UTC by triwahyuu

here I used the builtin [tensorboad writer from PyTorch](https://pytorch.org/docs/stable/tensorboard.html) which was officially supported in PyTorch 1.2.0. I also removed the warning for the use of torch.uint8 for indexing.

2021-01-06 18:21 UTC, Flova requested changes

2021-01-06 18:21 UTC, Flova commented on requirements.txt
> +torch>=1.2
Is this bump really needed?

2021-01-06 18:21 UTC, Flova commented on utils/utils.py
> +    BoolTensor = torch.cuda.BoolTensor if pred_boxes.is_cuda else torch.BoolTensor
This is not part of this pull request. Could you remove it. Otherwise, this PR seems fine.

2021-01-08 06:30 UTC, triwahyuu commented on requirements.txt
> +torch>=1.2
as I mentioned in the description, tensorboard support in pytorch is started on version 1.2

2021-01-08 06:32 UTC, triwahyuu commented on utils/utils.py
> +    BoolTensor = torch.cuda.BoolTensor if pred_boxes.is_cuda else torch.BoolTensor
sory that this might be unrelated, I'm trying to remove the warning from pytorch, as it is recommended to use BoolTensor for boolean operation, e.g. tensor masking

2021-01-08 09:58 UTC, Flova commented on utils/utils.py
> +    BoolTensor = torch.cuda.BoolTensor if pred_boxes.is_cuda else torch.BoolTensor
I know that issue and it is fixed on the current master due to PR #541

2021-01-08 09:59 UTC, Flova commented on requirements.txt
> +torch>=1.2
Oh sorry nvm

2021-01-08 11:32 UTC, triwahyuu commented on utils/utils.py
> +    BoolTensor = torch.cuda.BoolTensor if pred_boxes.is_cuda else torch.BoolTensor
ohh sorry, will remove this one

2021-01-08 12:16 UTC, Flova approved these changes
Thanks for your contribution!

2021-01-08 12:17 UTC, merged