Add poetry package management
eriklindernoren/PyTorch-YOLOv3 pull request #660
Opened 2021-04-09 18:15 UTC by Flova

# Add Poetry package management
This PR converts this repo into a [poetry](https://python-poetry.org/) package. 

## Why

* This isolates the project inside a virtual environment and therefore reduces issues due to incompatible dependencies. 
* It makes it project a proper python package. Which simplifies imports and allows it to be imported by other applications. This combined with #618  results in an API that can be called from other Python scripts. 
* Poetry can be used to publish the code to [pipy.org](https://pipy.org). So other projects are able to depend on it and use the new API e.g. for simple inference.
* It also adds proper CLI commands instead of the `python3 foo.py` script calls.
* Add CI with flake8 and small training, test, and detection. 

## Issues
Closes #630

2021-04-11 17:51 UTC, jaagut requested changes
I really love these changes! Much WOW!
This addresses soo many small and large issues and helps troubleshooting in the future.

Besides, I have a few questions and suggestions.

2021-04-11 17:51 UTC, jaagut commented on README.md
> +You need join the virtual enviroment by runing `poetry shell` in this directory before running any of the following commands without the `poetry run` prefix. Also have a look at the other installing
```suggestion
You need to join the virtual enviroment by runing `poetry shell` in this directory before running any of the following commands without the `poetry run` prefix.
Also have a look at the other installing method, if you want to use the commands everywhere without opening a poetry-shell.
```
I think, it is a little bit unclear, what the difference between `shell` and `run` is, and why to use `shell`, when not using `run`.

2021-04-11 17:51 UTC, jaagut commented on README.md
> +bash download_weights.sh
```suggestion
./weights/download_weights.sh
```
The bash command is not needed, as the file has a shebang, but I don't know, if this file has the executable flag...

2021-04-11 17:51 UTC, jaagut commented on README.md
> +bash get_coco_dataset.sh
```suggestion
./data/get_coco_dataset.sh
```
Same as above

2021-04-11 17:51 UTC, jaagut commented on README.md
> +This installation method is less isolated and may conflict with other packages. It also only includes the code. Weights and the COCO dataset need to be installed as stated above. With this beeing sai
```suggestion
This installation method is recommended, if you want to use this package as dependency in another python project.
This method only includes the code, is less isolated and may conflict with other packages.
Weights and the COCO dataset need to be downloaded as stated above.
See __API__ for further information regarding the packages API.
It also enables the CLI tools `yolo-detect`, `yolo-train`, and `yolo-test` everywhere without any additional commands.
```
A few things are unclear to me:

- Why would this conflict with other packages? Is there anything special, compared to other published packages, that makes this more risky?
- Weights and dataset can not be `installed`or downloaded as stated above. The package is installed in a other directory, which also should not contain data.
- What do you mean by `enabling`cli tools?

2021-04-11 17:51 UTC, jaagut commented on README.md
> +Evaluates the model on COCO test dataset.
```suggestion
Evaluates the model on COCO test dataset.
To download this dataset as well as weights, see above.
```

2021-04-11 17:51 UTC, jaagut commented on README.md
> +bash create_custom_model.sh <num-classes> # Will create custom model 'yolov3-custom.cfg'
```suggestion
./config/create_custom_model.sh <num-classes>  # Will create custom model 'yolov3-custom.cfg'
```
See above

2021-04-11 17:51 UTC, jaagut commented on pytorchyolo/train.py
> +            if args.verbose:
This `if` statement could be moved up to line 188.

2021-04-11 17:54 UTC, jaagut commented
Please also adapt the PR description, as it says nothing about the CI (#316) and nothing about the pep8.

2021-04-16 15:04 UTC, Flova commented on .github/workflows/main.yml
> +        run: poetry run yolo-train --data config/custom.data  --model config/yolov3.cfg --epochs 5
Indeed, but on the other hand, the evaluation module call, the transfer of the model, and the logging are tested this way.

2021-04-16 15:21 UTC, Flova commented on README.md
> +This installation method is less isolated and may conflict with other packages. It also only includes the code. Weights and the COCO dataset need to be installed as stated above. With this beeing sai
* Not really, but if the installs another project without a venv with numpy==4.2.0 and we require numpy==6.9.0 it may conflicts and results in undefined behavior.
* The code is installed in a "hidden" system folder so if the user runs e.g. `yolo-train` he needs to use the correct path for the weights file. This shouldn't be a problem if he runs the command in the root of the cloned git repo because that would match the default paths.
* You are able to use them just like `git` or any other command in the `PATH`without sourcing your venv aka. run `poetry shell`or something simmilar.

2021-04-16 15:46 UTC, jaagut approved these changes

2021-04-16 15:46 UTC, jaagut commented on README.md
> +This installation method is recommended, if you want to use this package as dependency in another python project.
```suggestion
This installation method is recommended, if you want to use this package as a dependency in another python project.
```

2021-04-16 15:46 UTC, jaagut commented on README.md
> +For more advanced usage look at the method doc strings.
```suggestion
For more advanced usage look at the method's doc strings.
```

2021-04-16 15:48 UTC, merged